# Generated by Django 4.2.4 on 2023-09-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
