# Generated by Django 4.2.4 on 2023-09-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('image1', models.ImageField(upload_to='projects', verbose_name='Imagen1')),
                ('Seconddes1', models.TextField(verbose_name='Descripcion')),
                ('image2', models.ImageField(upload_to='projects', verbose_name='Imagen2')),
                ('Seconddes2', models.TextField(verbose_name='Descripcion')),
                ('image3', models.ImageField(upload_to='projects', verbose_name='Imagen3')),
                ('Seconddes3', models.TextField(verbose_name='Descripcion')),
                ('image4', models.ImageField(upload_to='projects', verbose_name='Imagen4')),
                ('Seconddes4', models.TextField(verbose_name='Descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
            ],
            options={
                'verbose_name': 'Contenido',
                'verbose_name_plural': 'Contenidos',
                'ordering': ['-created'],
            },
        ),
    ]
